/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thinh;

import java.util.ArrayList;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import responsitory.KhuyenMaiRe;

/**
 *
 * @author thinh
 */
public class Form_KhuyenMai extends javax.swing.JPanel {

    ArrayList<KhuyenMai> listView = new ArrayList<>();
    DefaultTableModel model;
    KhuyenMaiRe kms = new KhuyenMaiRe();
    private String MaKM;
    private String TenKM;
    private String DieuKien;
    private String PhanTramKM;
    private String NgayBD;
    private String NgayKT;

    /**
     * Creates new form KhuyenMaiF
     */
    public Form_KhuyenMai() throws SQLException {
        initComponents();
        listView = kms.getAllKhuyenMai();
        filltoTable();
        fillTableToForm(WIDTH);
        txtMa.setText("");
        txtTen.setText("");
        txtDK.setText("");
        txtPT.setText("");
        txtBĐ.setText("");
        txtKT.setText("");
    }

    public void filltoTable() {
        model = (DefaultTableModel) tblKhuyenMai.getModel();
        model.setRowCount(0);
        for (KhuyenMai khuyenmai : listView) {
            model.addRow(khuyenmai.toRowTable());
        }
    }

    public void fillTableToForm(int index) {
        KhuyenMai khuyenMai = listView.get(index);
        txtMa.setText(khuyenMai.getMaKM());
        txtTen.setText(khuyenMai.getTenKM());
        txtDK.setText(khuyenMai.getDieuKien());
        txtPT.setText(khuyenMai.getPhanTramKM());
        txtBĐ.setText(khuyenMai.getNgayBD());
        txtKT.setText(khuyenMai.getNgayKT());
    }

    public boolean isValidDate(String dateStr) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            sdf.parse(dateStr);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    private void resetForm() {
        txtMa.setText("");
        txtTen.setText("");
        txtDK.setText("");
        txtPT.setText("");
        txtBĐ.setText("");
        txtKT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        txtDK = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        txtBĐ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        txtPT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();

        jLabel8.setText("Phần Trăm:");

        jLabel9.setText("Ngày KT:");

        btnAdd.setBackground(new java.awt.Color(204, 204, 255));
        btnAdd.setForeground(new java.awt.Color(204, 51, 0));
        btnAdd.setText("Thêm Voucher");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 204, 255));
        btnSua.setForeground(new java.awt.Color(204, 0, 51));
        btnSua.setText("Sửa Voucher");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 204, 255));
        btnXoa.setForeground(new java.awt.Color(204, 0, 51));
        btnXoa.setText("Xóa Vocuher");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tìm kiếm:");

        jLabel4.setText("Mã Voucher:");

        jLabel5.setText("Điều Kiện:");

        btnSearch.setBackground(new java.awt.Color(153, 255, 153));
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Quản Lí Bán Điện Thoại");

        jLabel6.setText("Ngày BĐ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("DANH SÁCH VOUCHER");

        jLabel7.setText("Tên Voucher:");

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Voucher", "Tên Voucher", "Điều Kiện", "Phần Trăm", "Ngày Bắt Đầu", "Ngày Kết Thúc"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhuyenMai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDK, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAdd))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtBĐ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedIndex = tblKhuyenMai.getSelectedRow();
        if (selectedIndex >= 0 && selectedIndex < listView.size()) {
            KhuyenMai selectedKM = listView.get(selectedIndex);
            // Xóa khỏi cơ sở dữ liệu
            kms.XoaVoucher(selectedKM);
            // Xóa khỏi danh sách
            listView.remove(selectedIndex);
            // Cập nhật bảng hiển thị
            filltoTable();
            // Đặt lại form nhập
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một voucher để xóa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = txtSearch.getText().trim().toLowerCase();
        ArrayList<KhuyenMai> filteredList = new ArrayList<>();

        for (KhuyenMai km : listView) {
            if (km.getMaKM().toLowerCase().contains(searchText)
                || km.getTenKM().toLowerCase().contains(searchText)
                || km.getDieuKien().toLowerCase().contains(searchText)
                || km.getPhanTramKM().toLowerCase().contains(searchText)
                || km.getNgayBD().toLowerCase().contains(searchText)
                || km.getNgayKT().toLowerCase().contains(searchText)) {
                filteredList.add(km);
            }
        }

        model.setRowCount(0);
        for (KhuyenMai km : filteredList) {
            model.addRow(km.toRowTable());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedIndex = tblKhuyenMai.getSelectedRow();
        if (selectedIndex >= 0 && selectedIndex < listView.size()) {
            // Cập nhật dữ liệu từ các JTextField
            String tenKM = txtTen.getText().trim();
            String dieuKien = txtDK.getText().trim();
            String phanTramKM = txtPT.getText().trim();
            String ngayBD = txtBĐ.getText().trim();
            String ngayKT = txtKT.getText().trim();

            if (tenKM.isEmpty() || dieuKien.isEmpty() || phanTramKM.isEmpty() || ngayBD.isEmpty() || ngayKT.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
                return;
            }

            try {
                int ptKM = Integer.parseInt(phanTramKM);
                if (ptKM < 0 || ptKM > 100) {
                    JOptionPane.showMessageDialog(this, "Phần trăm khuyến mãi phải nằm trong khoảng từ 0 đến 100.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Phần trăm khuyến mãi phải là số nguyên.");
                return;
            }

            // Kiểm tra điều kiện phải là số nguyên
            try {
                Integer.parseInt(dieuKien);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Điều kiện phải là số nguyên.");
                return;
            }

            if (!isValidDate(ngayBD) || !isValidDate(ngayKT)) {
                JOptionPane.showMessageDialog(this, "Ngày không hợp lệ. Định dạng ngày phải là yyyy-MM-dd.");
                return;
            }

            KhuyenMai selectedKM = listView.get(selectedIndex);

            selectedKM.setTenKM(tenKM);
            selectedKM.setDieuKien(dieuKien);
            selectedKM.setPhanTramKM(phanTramKM);
            selectedKM.setNgayBD(ngayBD);
            selectedKM.setNgayKT(ngayKT);

            kms.updateVoucher(selectedKM);
            listView.set(selectedIndex, selectedKM);

            filltoTable();
            // Đặt lại form nhập
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một voucher để sửa");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String maKM = txtMa.getText().trim();
        String tenKM = txtTen.getText().trim();
        String dieuKien = txtDK.getText().trim();
        String phanTramKM = txtPT.getText().trim();
        String ngayBD = txtBĐ.getText().trim();
        String ngayKT = txtKT.getText().trim();

        // Validate dữ liệu
        if (maKM.isEmpty() || tenKM.isEmpty() || dieuKien.isEmpty() || phanTramKM.isEmpty() || ngayBD.isEmpty() || ngayKT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
            return;
        }

        try {
            int ptKM = Integer.parseInt(phanTramKM);
            if (ptKM < 0 || ptKM > 100) {
                JOptionPane.showMessageDialog(this, "Phần trăm khuyến mãi phải nằm trong khoảng từ 0 đến 100.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Phần trăm khuyến mãi phải là số nguyên.");
            return;
        }
        // Kiểm tra điều kiện phải là số nguyên
        try {
            Integer.parseInt(dieuKien);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Điều kiện phải là số nguyên.");
            return;
        }
        // Kiểm tra định dạng ngày
        if (!isValidDate(ngayBD) || !isValidDate(ngayKT)) {
            JOptionPane.showMessageDialog(this, "Ngày không hợp lệ. Định dạng ngày phải là năm-tháng-ngày.");
            return;
        }

        // Tạo một đối tượng KhuyenMai mới
        KhuyenMai newKM = new KhuyenMai(maKM, tenKM, dieuKien, phanTramKM, ngayBD, ngayKT);
        // Thêm vào danh sách
        listView.add(newKM);
        // Thêm vào cơ sở dữ liệu
        kms.addVoucher(newKM);
        // Cập nhật bảng hiển thị
        filltoTable();
        // Đặt lại form nhập
        resetForm();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        int index = tblKhuyenMai.getSelectedRow();
        fillTableToForm(index);
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtBĐ;
    private javax.swing.JTextField txtDK;
    private javax.swing.JTextField txtKT;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtPT;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
