/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form_View;

import DTO.DTO_DanhSachSanPham;
import DTO.DTO_SanPham_CTSP;
import Model.MD_Ctsp_CN;
import OuputFile.DanhSachXuatFile;
import Service.SV_DanhSachSanPham;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 84904
 */
public class Form_XuatFile extends javax.swing.JFrame {

    List<DTO_SanPham_CTSP> list1 = new ArrayList<>();
    List<DTO_DanhSachSanPham> list2 = new ArrayList<>();
    List<DTO_DanhSachSanPham> list3 = new ArrayList<>();
    List<DTO_SanPham_CTSP> listCTSP = new ArrayList<>();
    SV_DanhSachSanPham SV_DANHSACHSANPHAM = new SV_DanhSachSanPham();

    /**
     * Creates new form Form_XuatFile
     */
    public Form_XuatFile(List<DTO_SanPham_CTSP> ctsp_XuatFile_daChon, List<DTO_DanhSachSanPham> lisstSP) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(Form_XuatFile.DISPOSE_ON_CLOSE);//sẽ được đóng và tài nguyên của nó sẽ được giải phóng, nhưng chương trình sẽ vẫn tiếp tục chạy.
        btnExcel_AllSP.setBackground(Color.white);
        btnExcel_dachon.setBackground(Color.white);
//        btnGG_daChon.setBackground(Color.white);
//        btngg_AllSP.setBackground(Color.white);

        for (DTO_SanPham_CTSP ctsp : ctsp_XuatFile_daChon) {

            list1.add(ctsp);
        }
        for (DTO_DanhSachSanPham sp : lisstSP) {

            list2.add(sp);
        }
        list3 = SV_DANHSACHSANPHAM.selectAllDSS();
        listCTSP = SV_DANHSACHSANPHAM.selectAllCTSP();
//        System.out.println("+++++++++++++++++++++++++++++++++++++++");
//        if(listCTSP.isEmpty()){
//            System.out.println("Lisst listCTSP null ");
//        }else{
//            for (DTO_SanPham_CTSP m : listCTSP) {
//                    System.out.println("Lisst chi tieets sp "+m);
//
//        }
//        }
    }

    public void setColerBtn() {
        btnExcel_AllSP.setBackground(Color.white);
        btnExcel_dachon.setBackground(Color.white);
//        btnGG_daChon.setBackground(Color.white);
//        btngg_AllSP.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Custom1 = new Swing_Custom.Panel_Custom();
        jLabel10 = new javax.swing.JLabel();
        panel_Custom2 = new Swing_Custom.Panel_Custom();
        btnExcel_AllSP = new javax.swing.JButton();
        panel_Custom3 = new Swing_Custom.Panel_Custom();
        btnExcel_dachon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Custom1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Xuất File");

        panel_Custom2.setBackground(new java.awt.Color(0, 204, 204));
        panel_Custom2.setBorder(javax.swing.BorderFactory.createTitledBorder("Xuất tất cả Sản Phẩm"));

        btnExcel_AllSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Excel.png"))); // NOI18N
        btnExcel_AllSP.setText("EXCEL");
        btnExcel_AllSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcel_AllSP.setIconTextGap(60);
        btnExcel_AllSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcel_AllSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcel_AllSPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExcel_AllSPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExcel_AllSPMouseReleased(evt);
            }
        });
        btnExcel_AllSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel_AllSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Custom2Layout = new javax.swing.GroupLayout(panel_Custom2);
        panel_Custom2.setLayout(panel_Custom2Layout);
        panel_Custom2Layout.setHorizontalGroup(
            panel_Custom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Custom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcel_AllSP, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_Custom2Layout.setVerticalGroup(
            panel_Custom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Custom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcel_AllSP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panel_Custom3.setBackground(new java.awt.Color(102, 204, 255));
        panel_Custom3.setBorder(javax.swing.BorderFactory.createTitledBorder("Xuất theo Sản Phẩm đã chọn"));

        btnExcel_dachon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Excel.png"))); // NOI18N
        btnExcel_dachon.setText("EXCEL");
        btnExcel_dachon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcel_dachon.setIconTextGap(60);
        btnExcel_dachon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcel_dachonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcel_dachonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExcel_dachonMouseReleased(evt);
            }
        });
        btnExcel_dachon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel_dachonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Custom3Layout = new javax.swing.GroupLayout(panel_Custom3);
        panel_Custom3.setLayout(panel_Custom3Layout);
        panel_Custom3Layout.setHorizontalGroup(
            panel_Custom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Custom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcel_dachon, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_Custom3Layout.setVerticalGroup(
            panel_Custom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Custom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcel_dachon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_Custom1Layout = new javax.swing.GroupLayout(panel_Custom1);
        panel_Custom1.setLayout(panel_Custom1Layout);
        panel_Custom1Layout.setHorizontalGroup(
            panel_Custom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Custom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Custom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Custom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Custom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_Custom1Layout.setVerticalGroup(
            panel_Custom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Custom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Custom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Custom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Custom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Custom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcel_AllSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel_AllSPActionPerformed
        // TODO add your handling code here:
        System.out.println("Đã chọn xuất All sanr phẩm ra excel");
        new DanhSachXuatFile(listCTSP, list3).setVisible(true);
    }//GEN-LAST:event_btnExcel_AllSPActionPerformed

    private void btnExcel_AllSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_AllSPMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExcel_AllSPMouseReleased

    private void btnExcel_dachonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_dachonMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExcel_dachonMouseReleased

    private void btnExcel_AllSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_AllSPMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcel_AllSPMousePressed

    private void btnExcel_AllSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_AllSPMouseEntered
        // TODO add your handling code here:
        btnExcel_AllSP.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnExcel_AllSPMouseEntered

    private void btnExcel_AllSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_AllSPMouseExited
        // TODO add your handling code here:
        setColerBtn();
    }//GEN-LAST:event_btnExcel_AllSPMouseExited

    private void btnExcel_dachonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_dachonMouseExited
        // TODO add your handling code here:
        setColerBtn();

    }//GEN-LAST:event_btnExcel_dachonMouseExited

    private void btnExcel_dachonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcel_dachonMouseEntered
        // TODO add your handling code here:
        btnExcel_dachon.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnExcel_dachonMouseEntered

    private void btnExcel_dachonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel_dachonActionPerformed
        // TODO add your handling code here:
        System.out.println("Đã chọn xuất sanr phẩm được chọn ra excel");
        if (list1.isEmpty() || list2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xuất file ở [Danh Sách Sản Phẩm] trước khi xuất file .", "Thông Báo Hệ Thống !", 0);
        } else if (!list1.isEmpty() || !list2.isEmpty()) {
            new DanhSachXuatFile(list1, list2).setVisible(true);
        }
    }//GEN-LAST:event_btnExcel_dachonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_XuatFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_XuatFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_XuatFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_XuatFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_XuatFile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel_AllSP;
    private javax.swing.JButton btnExcel_dachon;
    private javax.swing.JLabel jLabel10;
    private Swing_Custom.Panel_Custom panel_Custom1;
    private Swing_Custom.Panel_Custom panel_Custom2;
    private Swing_Custom.Panel_Custom panel_Custom3;
    // End of variables declaration//GEN-END:variables
}
